PierresTreats/Models/Treat.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace PierresTreats.Models
{
  public class Treat
  {
    public int TreatId { get; set; }
    public string Name { get; set; }
    public List<TreatFlavor> JoinEntities { get; set; }
    public ApplicationUser User {get; set; }
  }
}

PierresTreats/Controllers/FlavorsController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using System.Threading.Tasks;
using System.Security.Claims;
using PierresTreats.Models;

namespace PierresTreats.Controllers
{
  [Authorize]
  public class FlavorsController : Controller
  {
    private readonly PierresTreatsContext _db;
    private readonly UserManager<ApplicationUser> _userManager;
    public FlavorsController(UserManager<ApplicationUser> userManager, PierresTreatsContext db)
    {
      _userManager = userManager;
      _db = db;
    }

    [AllowAnonymous]
    public ActionResult Index()
    {
      return View(_db.Flavors.ToList());
    }

    [AllowAnonymous]
    public ActionResult Details(int id)
    {
      Flavor thisFlavor = _db.Flavors
                              .Include(flavor => flavor.JoinEntities)
                              .ThenInclude(join => join.Treat)
                              .FirstOrDefault(flavor => flavor.FlavorId == id);
      return View(thisFlavor);
    }

    // READ functions ^^^^
    //------------------------------------------------------------------
    // CREATE functions vvvv

    [Authorize(Roles = "Administrator")]
    public ActionResult Create()
    {
      try
      {
        return View();
      }
      catch
      {
        return View("Accounts", "AccessDenied");
      }

    }

    [HttpPost]
    public async Task<ActionResult> Create(Flavor flavor)
    {
      if (!ModelState.IsValid)
      {
        return View(flavor);
      }
      else
      {
        string userId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
        ApplicationUser currentUser = await _userManager.FindByIdAsync(userId);
        flavor.User = currentUser;
        _db.Flavors.Add(flavor);
        _db.SaveChanges();
        return RedirectToAction("Index");
      }
    }

    [Authorize(Roles = "Administrator")]
    public ActionResult AddTreat(int id)
    {
      try
      {
        Flavor thisFlavor = _db.Flavors.FirstOrDefault(flavors => flavors.FlavorId == id);
        ViewBag.TreatId = new SelectList(_db.Treats, "TreatId", "Name");
        return View(thisFlavor);
      }
      catch
      {
        return View("Accounts", "AccessDenied");
      }


    }

    [HttpPost]
    public ActionResult AddTreat(Flavor flavor, int treatId)
    {
#nullable enable
      TreatFlavor? joinEntity = _db.TreatFlavors.FirstOrDefault(join => (join.TreatId == treatId && join.FlavorId == flavor.FlavorId));
#nullable disable
      if (joinEntity == null && treatId != 0)
      {
        _db.TreatFlavors.Add(new TreatFlavor() { TreatId = treatId, FlavorId = flavor.FlavorId });
        _db.SaveChanges();
      }
      return RedirectToAction("Details", new { id = flavor.FlavorId });
    }

    // CREATE functions ^^^^
    //------------------------------------------------------------------
    // UPDATE functions vvvv

    [Authorize(Roles = "Administrator")]
    public ActionResult Edit(int id)
    {
      try
      {
        Flavor thisFlavor = _db.Flavors.FirstOrDefault(flavors => flavors.FlavorId == id);
        return View(thisFlavor);
      }
      catch
      {
        return View("Accounts", "AccessDenied");
      }
    }

    [HttpPost]
    public ActionResult Edit(Flavor flavor)
    {
      _db.Flavors.Update(flavor);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    // UPDATE functions ^^^^
    //------------------------------------------------------------------
    // DELETE functions vvvv

    [Authorize(Roles = "Administrator")]
    public ActionResult Delete(int id)
    {
      try
      {
        Flavor thisFlavor = _db.Flavors.FirstOrDefault(flavors => flavors.FlavorId == id);
        return View(thisFlavor);
      }
      catch
      {
        return View("Accounts", "AccessDenied");
      }

    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      Flavor thisFlavor = _db.Flavors.FirstOrDefault(flavors => flavors.FlavorId == id);
      _db.Flavors.Remove(thisFlavor);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [Authorize(Roles = "Administrator")]
    [HttpPost]
    public ActionResult DeleteJoin(int joinId)
    {
      try
      {
        TreatFlavor joinEntry = _db.TreatFlavors.FirstOrDefault(e => e.TreatFlavorId == joinId);
        _db.TreatFlavors.Remove(joinEntry);
        _db.SaveChanges();
        return RedirectToAction("Index");
      }
      catch
      {
        return View("Accounts", "AccessDenied");
      }

    }

    // DELETE functions ^^^^
  }
}

PierresTreats/Controllers/TreatsController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using System.Threading.Tasks;
using System.Security.Claims;
using PierresTreats.Models;

namespace PierresTreats.Controllers
{
  [Authorize]
  public class TreatsController : Controller
  {
    private readonly PierresTreatsContext _db;
    private readonly UserManager<ApplicationUser> _userManager;
    public TreatsController(UserManager<ApplicationUser> userManager, PierresTreatsContext db)
    {
      _userManager = userManager;
      _db = db;
    }

    [AllowAnonymous]
    public ActionResult Index()
    {
      return View(_db.Treats.ToList());
    }

    [AllowAnonymous]
    public ActionResult Details(int id)
    {
      Treat thisTreat = _db.Treats
                              .Include(treat => treat.JoinEntities)
                              .ThenInclude(join => join.Flavor)
                              .FirstOrDefault(treat => treat.TreatId == id);
      return View(thisTreat);
    }

    // READ functions ^^^^
    //------------------------------------------------------------------
    // CREATE functions vvvv
    [Authorize(Roles = "Administrator")]
    public ActionResult Create()
    {
      try
      {
        return View();
      }
      catch
      {
        return View("Accounts", "AccessDenied");
      }

    }

    [HttpPost]
    public async Task<ActionResult> Create(Treat treat)
    {
      if (!ModelState.IsValid)
      {
        return View();
      }
      else
      {
        string userId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
        ApplicationUser currentUser = await _userManager.FindByIdAsync(userId);
        treat.User = currentUser;
        _db.Treats.Add(treat);
        _db.SaveChanges();
        return RedirectToAction("Index");
      }
    }

    [Authorize(Roles = "Administrator")]
    public ActionResult AddFlavor(int id)
    {

      try
      {
        Treat thisTreat = _db.Treats.FirstOrDefault(treats => treats.TreatId == id);
        ViewBag.FlavorId = new SelectList(_db.Flavors, "FlavorId", "Kind");
        return View(thisTreat);
      }
      catch
      {
        return View("Accounts", "AccessDenied");
      }

    }

    [HttpPost]
    public ActionResult AddFlavor(Treat treat, int flavorId)
    {
#nullable enable
      TreatFlavor? joinEntity = _db.TreatFlavors.FirstOrDefault(join => (join.FlavorId == flavorId && join.TreatId == treat.TreatId));
#nullable disable
      if (joinEntity == null && flavorId != 0)
      {
        _db.TreatFlavors.Add(new TreatFlavor() { FlavorId = flavorId, TreatId = treat.TreatId });
        _db.SaveChanges();
      }
      return RedirectToAction("Details", new { id = treat.TreatId });
    }

    // CREATE functions ^^^^
    //------------------------------------------------------------------
    // UPDATE functions vvvv

    [Authorize(Roles = "Administrator")]
    public ActionResult Edit(int id)
    {
      try
      {
        Treat thisTreat = _db.Treats.FirstOrDefault(treats => treats.TreatId == id);
        return View(thisTreat);
      }
      catch
      {
        return View("Accounts", "AccessDenied");
      }

    }

    [HttpPost]
    public ActionResult Edit(Treat treat)
    {
      _db.Treats.Update(treat);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    // UPDATE functions ^^^^
    //------------------------------------------------------------------
    // DELETE functions vvvv


    [Authorize(Roles = "Administrator")]
    public ActionResult Delete(int id)
    {
      try
      {
        Treat thisTreat = _db.Treats.FirstOrDefault(treats => treats.TreatId == id);
        return View(thisTreat);
      }
      catch
      {
        return View("Accounts", "AccessDenied");
      }

    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      Treat thisTreat = _db.Treats.FirstOrDefault(treats => treats.TreatId == id);
      _db.Treats.Remove(thisTreat);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [Authorize(Roles = "Administrator")]
    [HttpPost]
    public ActionResult DeleteJoin(int joinId)
    {
      try
      {
        TreatFlavor joinEntry = _db.TreatFlavors.FirstOrDefault(e => e.TreatFlavorId == joinId);
        _db.TreatFlavors.Remove(joinEntry);
        _db.SaveChanges();
        return RedirectToAction("Index");
      }
      catch
      {
        return View("Accounts", "AccessDenied");
      }

    }

    // DELETE functions ^^^^
  }
}

PierresTreats/Views/Treats/AddFlavor.cshtml
@{
  Layout = "_Layout";
}
@model PierresTreats.Models.Treat

<h2>Add Flavors to this Treat</h2>

<h4>@Html.DisplayFor(model => model.Name)</h4>
<p>This treat tastes like:</p>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.TreatId)

  @Html.Label("Select Flavor")
  <br>
  @Html.DropDownList("FlavorId")
  <br>
  <input type="submit" value="MAKE IT SO"/>
}

<hr />
<p>@Html.ActionLink("Back to Home", "Index", "Home")</p>
<p>@Html.ActionLink("Back to Treats", "Index")</p>
<p>@Html.ActionLink("See all Flavors", "Index", "Flavors")</p>

PierresTreats/Views/Treats/Create.cshtml
@{
  Layout = "_Layout";
}

@model PierresTreats.Models.Treat

<h2>Design a Treat!</h2>

<p>@Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger", @style = "font-weight: 600;" })</p>

@using (Html.BeginForm())
{
  <label>This treat should be called a(n)...? </label>
  @Html.TextBoxFor(model => model.Name)
  <br>
  <input type="submit" value="Put it on display!">
}

<hr />
<p>@Html.ActionLink("Back to Home", "Index", "Home")</p>
<p>@Html.ActionLink("See all Treats", "Index")</p>
<p>@Html.ActionLink("See all Flavors", "Index", "Flavors")</p>

PierresTreats/Views/Treats/Delete.cshtml
@{
  Layout = "_Layout";
}

@model PierresTreats.Models.Treat

<h2>Confirm Delete Flavor:</h2>

@Html.DisplayNameFor(model => model.Name): <span> </span> @Html.DisplayFor(model => model.Name)

@using (Html.BeginForm())
{
  <p>People just aren't in the market for these right now.</p>
  <input type="submit" value="Make Room for More Treats!" />
}

<hr />
<p>@Html.ActionLink("Back to Home", "Index", "Home")</p>
<p>@Html.ActionLink("Edit this Treat", "Edit", new { id = Model.TreatId})</p>
<p>@Html.ActionLink("Back to Treats", "Index")</p>
<p>@Html.ActionLink("Back to Flavors", "Index", "Flavors")</p>

PierresTreats/Views/Treats/Details.cshtml
@{
  Layout = "_Layout";
}

@using PierresTreats.Models
@model PierresTreats.Models.Treat

<h2> Treat Details:</h2>
<hr />

<h4>@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)</h4>

@if (@Model.JoinEntities.Count == 0)
{
  <p>This Treat has no Flavors!</p>
  <p>(Wait, that can't be right!)</p>
  <p>@Html.ActionLink("Add Flavors to this Treat", "AddFlavor", new { id = Model.TreatId })</p>
}
else
{
  <h4>Treat Flavor Profile!</h4>
  @foreach (TreatFlavor treatFlavor in Model.JoinEntities)
  {
    <li>@treatFlavor.Flavor.Kind</li>
    @using (Html.BeginForm("DeleteJoin", "Treats"))
    {
      @Html.Hidden("joinId", @treatFlavor.TreatFlavorId)
      <input type="submit" value="Delete">
    }
  }
}

<hr />
<p>@Html.ActionLink("Back to Home", "Index", "Home")</p>
<p>@Html.ActionLink("Edit this Treat", "Edit", new { id = Model.TreatId})</p>
<p>@Html.ActionLink("Delete this Treat", "Delete", new { id = Model.TreatId })</p>
<p>@Html.ActionLink("Add more Flavors to this Treat!", "AddFlavor", new { id = Model.TreatId })</p>
<p>@Html.ActionLink("Back to Treats", "Index")</p>
<p>@Html.ActionLink("Back to Flavors", "Index", "Flavors")</p>

PierresTreats/Views/Treats/Edit.cshtml
@{
  Layout = "_Layout";
}

@model PierresTreats.Models.Treat

<h2>Edit a Treat</h2>

<h4>Edit this Treat!</h4>
<h4>@Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.TreatId)

  <label>This treat should be called a(n)...? </label>
  @Html.EditorFor(model => model.Name)
  <br>
  <input type="submit" value="Update!">
}

<hr />
<p>@Html.ActionLink("Back to Home", "Index", "Home")</p>
<p>@Html.ActionLink("See all Treats", "Index")</p>
<p>@Html.ActionLink("See all Flavors", "Index", "Flavors")</p>
<p>@Html.ActionLink("Add Flavors that taste like this Treat!", "AddFlavor", new { id = Model.TreatId })</p>

PierresTreats/Views/Treats/Index.cshtml
@{
  Layout = "_Layout";
}
<h2>Treats of Every Variety:</h2>
<hr />

@using PierresTreats.Models

@if (Model.Count == 0)
{
  <p>No Treats on File</p>
}
<ul>
  @foreach (Treat treat in Model)
  {
    <li>@Html.ActionLink($"{treat.Name}", "Details", new { id = treat.TreatId})</li>
  }
</ul>

<hr />
<p>@Html.ActionLink("Back to Home", "Index", "Home")</p>
<p>@Html.ActionLink("Add a Treat", "Create")</p>
<p>@Html.ActionLink("See all Flavors", "Index", "Flavors")</p>
<p>@Html.ActionLink("Create a Flavor", "Create", "Flavors")</p>